package servo.token;

public enum TokenType {

    // Single char tokens
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE,
    COMMA, DOT, MINUS, PLUS, SEMICOLON, SLASH, STAR, POW, MODULO,

    // 1 || 2 char tokens
    BANG, BANG_EQUAL, EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL, LESS, LESS_EQUAL,
    INCREMENT, DECREMENT,
    AND_AND, OR_OR,
    RIGHT_POINTER, LEFT_POINTER,

    // Literals
    IDENTIFIER, STRING,
    INTEGER, INTEGER64, FLOAT, FLOAT64,
    BYTE, CHAR, BOOLEAN,

    // Keywords
    AND, CLASS, ELSE, FALSE, FUNCTION, FOR, IF, NULL, OR, NaN,
    RETURN, SUPER, THIS, TRUE, VAR, LET, CONST, WHILE, CONSTANT,
    SCOPE, EXPORT, INTERFACE, ENUM, STRUCT, BREAK,
    ALLOCATE, DEALLOCATE, REFERENCE,

    PRINT, PRINTF, PRINTL, PRINTLF,

    EOF;

}
