name: Go Coverage Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.4' ]
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Display Go version
      run: go version

    - name: Build
      run: go build -v ./src/...

    - name: Test Coverage
      run: go test ./src/... -cover -json > TestResults-${{ matrix.go-version }}.json

    - name: Upload Go Coverage Test Results
      uses: actions/upload-artifact@v4
      with:
        name: Go-coverage-results-${{ matrix.go-version }}
        path: Servo-CoverageTestResults-${{ matrix.go-version }}.json
