name: Coverage Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23.4']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Go Dependencies
        run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest

      - name: Display Go version
        run: go version

      - name: Build Servo
        run: go build -v ./src/...

      - name: Test Servo Coverage
        run: go test -cover -json ./src/... | go-ctrf-json-reporter -output reports/Servo-Coverage-Report.json

      - name: Publish Servo Test Summary Results
        run: npx github-actions-ctrf reports/Servo-Coverage-Report.json

      - name: Publish
        uses: actions/upload-artifact@v4
        with:
          name: Servo-Coverage-Report
          path: reports/Servo-Coverage-Report.json
